spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bl_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: buleng
    driver-class-name: com.mysql.cj.jdbc.Driver